version: '3'

services:
  radblog_postgresql:
    image: library/postgres:13
    container_name: radblog_postgresql
    volumes:
    - radblog_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - radblog_network
volumes:
  radblog_postgresql:
    external: true
networks:
  radblog_network:
    external: true

